### ISSUE TITLE
SF.lua | Версия R3

### ISSUE THREAD

**Issue by harlden** [SF-lua/SF.lua#7]
**Приветствую, дорогой разработчик данного скрипта. Я наверно целый день искал решение, как писать скрипты на версии сампа 0.3.7-R3, в итоге спросил у одного ютубера как решить данную проблему, то что sf не выпускали поддержку R3. Так вот, такой будет вопрос к Вам. Будет ли поддержка данного скрипта с версиями сампа R3. Я пишу в крмп, там R3 самп и получается когда я зашел ничего не происходит, зашел в афк. Когда выхожу из афк, меня мгновенно крашит. В чём заключается данная проблема? И получается зашел даже в самп обычный, всё нормально но как только я нажимаю F3 (проверка включен ли самп или sf), меня крашит. Можете помочь разобраться, желательно подробно, потому-что я желаю переделать свой AHK-скрипт в Lua-скрипт, но пока-что это не получается..**

**Comment by imring** [comment]
На данный момент в SF.lua нету поддержки версии 0.3.7-R3. Будет добавлена **после** релиза SF.lua 1.0.
